on: push

jobs:
    test-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/hello
              id: hello
              with:
                  who-to-greet: 'Mona the Octocat'
            - run: echo "The time ${{ steps.hello.outputs.time }}"