name: CI
on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'inq-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd inq-app
          echo "Installing dependencies..."
          npm install

      - name: Run check format code
        run: |
          cd inq-app
          echo "Running format..."
          npm run format:check

      - name: Run Coverage test
        run: |
          cd inq-app
          echo "Running coverage..."
          npm test -- --coverage
        env:
          CI: true
