name: CI
on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'inq-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: |
          cd inq-app
          npm install
          npm run format:check
          npm test -- --coverage
        env:
          CI: true
